USE ROLE ACCOUNT_MONITOR_OTI;

USE DATABASE ADMIN_UTLITIES ;  
USE SCHEMA COMMON_POLICIES;  

  
--OTI USERS & SECURITY INTEGRATIONS
SET OTI_SEC_INTEGRATION  = 'OTI_INTTEGRATION_NAME';

CREATE OR REPLACE AUTHENTICATION POLICY  OTI_PERSON_AUTH_POLICY
   AUTHENTICATION_METHODS=('SAML','PASSWORD','KEYPAIR','PROGRAMMATIC_ACCESS_TOKEN')
   CLIENT_TYPES=('ALL')
   SECURITY_INTEGRATIONS=($OTI_SEC_INTEGRATION)
   MFA_ENROLLMENT=REQUIRED
   MFA_AUTHENTICATION_METHODS=(PASSWORD)
   MFA_POLICY=(
       ALLOWED_METHODS=('PASSKEY','TOTP','DUO','OTP'))
   PAT_POLICY=(
       NETWORK_POLICY_EVALUATION=ENFORCED_REQUIRED,
       DEFAULT_EXPIRY_IN_DAYS=90,
       MAX_EXPIRY_IN_DAYS=365) ;
       
--AGENCY USERS & SECURITY INTEGRATIONS
SET AGENCY_SEC_INTEGRATION  = 'AGENCY_INTTEGRATION_NAME';

CREATE OR REPLACE AUTHENTICATION POLICY  AGENCY_PERSON_AUTH_POLICY
   AUTHENTICATION_METHODS=('SAML','KEYPAIR','PROGRAMMATIC_ACCESS_TOKEN')
   CLIENT_TYPES=('ALL')
   SECURITY_INTEGRATIONS=($AGENCY_SEC_INTEGRATION)
   PAT_POLICY=(
       NETWORK_POLICY_EVALUATION=ENFORCED_REQUIRED,
       DEFAULT_EXPIRY_IN_DAYS=90,
       MAX_EXPIRY_IN_DAYS=365);

--TEMPORARY AGENCY LOCAL ADMIN
CREATE OR REPLACE AUTHENTICATION POLICY  OTI_PERSON_AUTH_POLICY
   AUTHENTICATION_METHODS=('PASSWORD')
   CLIENT_TYPES=('SNOWFLAKE_UI')
   MFA_ENROLLMENT=REQUIRED
   MFA_AUTHENTICATION_METHODS=(PASSWORD)
   MFA_POLICY=(
       ALLOWED_METHODS=('PASSKEY','TOTP','DUO','OTP'));

    
--SERVICE USERS WITH BROAD RANGE OF METHODS AND CLIENT TYPES
CREATE OR REPLACE AUTHENTICATION POLICY SERVICE_AUTH_POLICY_GENERAL
   AUTHENTICATION_METHODS = ('KEYPAIR','PROGRAMMATIC_ACCESS_TOKEN', 'OAUTH')
   CLIENT_TYPES = ('DRIVERS','SNOWFLAKE_CLI','SNOWSQL')
   PAT_POLICY = (
       DEFAULT_EXPIRY_IN_DAYS=15,
       MAX_EXPIRY_IN_DAYS=90,
       NETWORK_POLICY_EVALUATION=ENFORCED_REQUIRED);


--SERVICE USERS WITH KEYPAIR AUTH FOR DRIVERS
CREATE OR REPLACE AUTHENTICATION POLICY SERVICE_AUTH_POLICY_KEYPAIR
   AUTHENTICATION_METHODS = ('KEYPAIR')
   CLIENT_TYPES = ('DRIVERS'); 


--SERVICE USERS WITH PAT TOKENS
CREATE OR REPLACE AUTHENTICATION POLICY SERVICE_AUTH_POLICY_PAT
   AUTHENTICATION_METHODS = ('PROGRAMMATIC_ACCESS_TOKEN')
   CLIENT_TYPES = ('DRIVERS','SNOWFLAKE_CLI','SNOWSQL')
   PAT_POLICY = (
       DEFAULT_EXPIRY_IN_DAYS=15,
       MAX_EXPIRY_IN_DAYS=90,
       NETWORK_POLICY_EVALUATION=ENFORCED_REQUIRED);

--SERVICE USERS WITH OAUTH
CREATE OR REPLACE AUTHENTICATION POLICY SERVICE_AUTH_POLICY_OAUTH
   AUTHENTICATION_METHODS = ('OAUTH')
   CLIENT_TYPES = ('DRIVERS','SNOWFLAKE_CLI','SNOWSQL');

---SET 
USE ROLE USERADMIN;
SHOW USERS;
ALTER USER USAGETEST SET AUTHENTICATION POLICY OTI_PERSON_AUTH_POLICY;     
